### ISSUE TITLE
Proposal new logo to SCHEDULE

### ISSUE THREAD

**Issue by ggabogarcia** [jianstm/Schedule#1]
Hello sir, I'm a graphic designer, I'm interested in open source projects. I would like to design a logo for your Project. I will be happy to collaborate with you :)

**Comment by jianstm** [comment]
Hi, @ggabogarcia , thank you for your enthusiasm! 
Welcome to contribute! Since `Schedule` doesn't have a logo for now, i bet i will accept your design as soon as i see it. 😉

**Comment by ggabogarcia** [comment]
Hello sir, here is my proposal of Timetable, using an hourglass represents the time, and next to the sign of approval means "set the time". This is what normally happens when we complete a schedule. :) I hope you like it. Any suggestion from you, just tell me :)

![schudelu](https://user-images.githubusercontent.com/35750428/43285047-69212fe2-90e3-11e8-93f1-47ac2f0af724.png)

**Comment by jianstm** [comment]
I love the talented idea of the sign! 👍
The only only thing i'd say is, the colors looks a little bit serious. I'm not sure if it will be better to be more vivid, what do you think? 🤔 
Anyway, the current proposal is totally good enough! 👏

**Comment by ggabogarcia** [comment]
:thinking: We could try other colors, I'll make some examples   :laughing:

**Comment by ggabogarcia** [comment]
Here some tests, I continued inclining for the first, and this new one that I liked also, I did not try it with warm colors like orange or yellow because in white backgrounds its intensity is reduced.

![schudelu 1](https://user-images.githubusercontent.com/35750428/43336444-8c7f233c-9196-11e8-9ab7-d195d8e9a0f6.png)

**Comment by jianstm** [comment]
@ggabogarcia Thank you for your great work! That's my first cooperation on github, 😁, that mean a lot to me, 🍻.
