### ISSUE TITLE
When I go to background and come foreground many times, the Timer stops

### ISSUE THREAD

**Issue by YiYiZheng** [jianstm/Schedule#14]
```
func applicationDidBecomeActive(_ application: UIApplication) {
        if let perSecondTask = perSecondTask {
            printLog("暂停的次数\(perSecondTask.suspends)")
            perSecondTask.resume()
        }
    }
```

**Comment by jianstm** [comment]
Hi @YiYiZheng , thank you for your feedback. This is a bug and has been fixed at [here](https://github.com/jianstm/Schedule/commit/a56ddc314dd102e0da0e93741ebb1e1a31702109), i also released 0.1.1 with this fixing, have a try!
Sorry for the confusion.
