### ISSUE TITLE
task.suspend() not work when app willResignActive

### ISSUE THREAD

**Issue by ownmas** [jianstm/Schedule#19]
If you call task.suspend() when app willResignActive and call task.resume() in didBecomeActive. It can't work.

**Comment by jianstm** [comment]
Hi, @ownmas , which version of Schedule are you using? Have you tried the new version [1.0.0](https://github.com/jianstm/Schedule/releases/tag/1.0.0)?

**Comment by ownmas** [comment]
@jianstm Yes, i understand, that this is the problem of all DispatchSourceTimer based delay managers.

**Comment by jianstm** [comment]
@ownmas Sorry? The latest version should fixed this issues, give it a try!
