### ISSUE TITLE
Schedule make the ipa file cannot be run on iOS

### ISSUE THREAD

**Issue by haithngn** [jianstm/Schedule#21]
I used Schedule in my project then export ipa file succeed also installed on my device.
Unfortunately, this app cannot be launch, the ios said "Unable to install "My App",

So I temporary remove Schedule then the app can launch now.

**Comment by jianstm** [comment]
Hi @haithngn , i have no idea on this, maybe try cleaning the project , or reinstalling? Do you also have other dependencies and are they working fine?
