### ISSUE TITLE
The countdown function is not accurate on the iPad iOS9.3.5

### ISSUE THREAD

**Issue by coderZjc** [jianstm/Schedule#24]
when I use the countdown function，I found it's not accurate on iPad running iOS 9.3.5
我发现在iOS9.3.5的系统上，倒计时功能无法正常计时。

![default](https://user-images.githubusercontent.com/24477024/48705872-64997300-ec35-11e8-880b-8be743dc7a32.jpg)

**Comment by jianstm** [comment]
我在 9.3 的 iPad 模拟器上试了一下没有问题啊，奇怪。

**Comment by coderZjc** [comment]
目前发现是9.3.5的系统上有问题，我在9.3.2的系统上运行都没问题

**Comment by coderZjc** [comment]
> 我在 9.3 的 iPad 模拟器上试了一下没有问题啊，奇怪。

目前发现是9.3.5的系统上有问题，我在9.3.2的系统上运行都没问题

**Comment by jianstm** [comment]
@coderZjc 抱歉我最近太忙了，周末我会找个 9.3.5 的模拟器好好看下。项目的原理很简单，如果你有时间的话不如直接修改本地源码 debug 下试试？

**Comment by coderZjc** [comment]
> > 我在 9.3 的 iPad 模拟器上试了一下没有问题啊，奇怪。
> 
> 目前发现是9.3.5的系统上有问题，我在9.3.2的系统上运行都没问题

刚发现10.3.3上也有这个问题

**Comment by jianstm** [comment]
@coderZjc 我昨天找了快一个钟都没有找到怎么安装这两个版本的模拟器，🥀；既然你有设备，有试过本地 debug 吗？用 submodule，发现问题的话欢迎提 pr！
