### ISSUE TITLE
estimatedNextExecution is nill

### ISSUE THREAD

**Issue by jangsy7883** [jianstm/Schedule#30]
`        let plan = Plan.every(.tuesday, .sunday).at("12:00").do {
            print("Happy holiday")
        }
            print(plan.timeline.estimatedNextExecution) //nill
`

When today is Tuesday, it seems that the schedule containing Tuesday is not registered.
I wonder if it was intended?

**Comment by jianstm** [comment]
Hi! Sorry for the late reply, I am too busy recently.
I just released 2.0.0, which should fix this issue, have a try! Don't forget to read the release log!

If the problem still exists, feel free to reopen this!

**Comment by rxvincent** [comment]
使用了Plan.every([.monday]).at("14:00:00")， 执行的时候已经过了这个时间了，estimatedNextExecutionDate为nil，因为此时interval为nil，Task创建的时候似乎不会执行_timer.schedule(after: interval)？
