### ISSUE TITLE
Task every day not work?

### ISSUE THREAD

**Issue by nhatquangz** [jianstm/Schedule#33]
I am confused how it work?
Assume that now is `Friday 15:10:00`

`let task = Plan.every(.friday).at(15,11).do {
	print("Execute task")
}`

But nothing printed at 15:11
Is there something wrong here?
(I tested in playground)

**Comment by jaimejazarenoiii** [comment]
'am encountering the same issue, nothing is being logged.

**Comment by liuchh** [comment]
am encountering the same issue

**Comment by jianstm** [comment]
Hi, guys! Sorry for the late reply, I am too busy recently. 
I just released [2.0.0](https://github.com/jianstm/Schedule/releases/tag/2.0.0), which should fix this issue, have a try! Don't forget to read the release log!

If the problem still exists, feel free to reopen this!
