### ISSUE TITLE
请问是否可添加倒数计时显示

### ISSUE THREAD

**Issue by laohanme** [jianstm/Schedule#36]
就如运用textlabel来显示倒数计时的时间

**Comment by jianstm** [comment]
抱歉，这个功能需要为 Schedule 增加 UIKit 的依赖，现在我觉得 Schedule 还是保持通用和简单要更好些，🍻

想要倒计时 Label 的功能可以试一下 [UICountingLabel](https://github.com/dataxpress/UICountingLabel) 或者 [EFCountingLabel](https://github.com/EFPrefix/EFCountingLabel)，它们看起来都很棒！

**Comment by laohanme** [comment]
回答甚好 谢谢您的建议 ❤️
