### ISSUE TITLE
指定week or month 无法do it

### ISSUE THREAD

**Issue by liuchh** [jianstm/Schedule#37]
Plan.every(.wednesday).at(14, 40).do() {}
使用swift4.0 xcode10.1 
 此方法 会造成内存泄露，并且没有执行do中的内容。真机和模拟器都会发生

**Comment by jianstm** [comment]
嗨, @liuchh , 感谢你的反馈，抱歉最近有些忙。这儿是有一个计算 bug ，刚刚发布的 [2.0.0](https://github.com/jianstm/Schedule/releases/tag/2.0.0) 应该修复了这个问题，试一下吧！

至于内存泄漏，在 Schedule 中，所有 task 默认会隐式地被一个内部 TaskCenter 持有，除非你显式地 `cancel` 它（就像你需要显式地 `invalidate` 一个 timer）。我也意识到了这个设计的确很容易导致内存泄漏，我已经在 2.0.0 里移除它啦。

再次感谢！🍻
