### ISSUE TITLE
mac开发

### ISSUE THREAD

**Issue by iizvv** [jianstm/Schedule#40]
我用下面的方法进行操作时, 项目没有任何反应
![image](https://user-images.githubusercontent.com/15830996/55781031-d5093980-5adb-11e9-8d89-272bd33a55a0.png)

**Comment by jianstm** [comment]
要持有返回的 task 对象哦，不然它会销毁的。

**Comment by iizvv** [comment]
👌。我试试

**Comment by iizvv** [comment]
非常感谢🙏
