### ISSUE TITLE
Ubuntu 16.04 package build has some errors, Mac is fine

### ISSUE THREAD

**Issue by LeeCenY** [jianstm/Schedule#6]
### Environment：
System：Ubuntu 16.04

Swfit version：Swift version 4.2-dev (LLVM da1c9a3ae4, Clang 78aa734eee, Swift 68f32fc2aa)
Target: x86_64-unknown-linux-gnu

Swift package tools version：3.1.0

```swift
import PackageDescription

let package = Package(
    name: "Test",
    targets: [],
    dependencies: [
        .Package(url: "https://github.com/PerfectlySoft/Perfect-HTTPServer.git", majorVersion: 3),
        .Package(url: "https://github.com/jianstm/Schedule.git", majorVersion: 0),
        ]
)

```

Swift build error
![image](https://user-images.githubusercontent.com/9047094/44441265-54ee9c00-a5fe-11e8-9313-70fa432571f6.png)

**Comment by jianstm** [comment]
Hi @LeeCenY , I just published a new release, that can be built on my ubuntu vm(16.04),  have a try!

I'm so happy someone is using Schedule on linux! But i gotta tell you, i didn't run test cases on linux.  They always failed when use `swift test`, : [

Looking forward to your further feedback! Any suggestion is welcome!
